authz/src/main/java/com/monkeyk/os/domain/oauth/AuthenticationIdGenerator.java
package com.monkeyk.os.domain.oauth;

/**
 * 15-6-20
 *
 * @author Shengzhao Li
 */

public interface AuthenticationIdGenerator {

    public String generate(String clientId, String username, String scope);

}

authz/src/main/java/com/monkeyk/os/domain/oauth/DefaultAuthenticationIdGenerator.java
package com.monkeyk.os.domain.oauth;

import org.apache.oltu.oauth2.common.OAuth;
import org.apache.oltu.oauth2.common.utils.OAuthUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;
import java.util.HashMap;
import java.util.Map;

/**
 * 15-6-20
 * <p/>
 * AuthenticationId 的生成器
 * MD5加密
 *
 * @author Shengzhao Li
 */
public class DefaultAuthenticationIdGenerator implements AuthenticationIdGenerator {

    private static final Logger LOGGER = LoggerFactory.getLogger(DefaultAuthenticationIdGenerator.class);

    public DefaultAuthenticationIdGenerator() {
    }


    public String generate(String clientId, String username, String scope) {
        Map<String, String> map = new HashMap<>();
        map.put(OAuth.OAUTH_CLIENT_ID, clientId);
        //check it is client only
        if (!clientId.equals(username)) {
            map.put(OAuth.OAUTH_USERNAME, username);
        }
        if (!OAuthUtils.isEmpty(scope)) {
            map.put(OAuth.OAUTH_SCOPE, scope);
        }

        return digest(map);
    }


    protected String digest(Map<String, String> map) {
        MessageDigest digest;
        try {
            digest = MessageDigest.getInstance("MD5");
        } catch (NoSuchAlgorithmException e) {
            LOGGER.warn("Digest error", e);
            throw new IllegalStateException("MD5 algorithm not available.  Fatal (should be in the JDK).");
        }

        try {
            byte[] bytes = digest.digest(map.toString().getBytes("UTF-8"));
            return String.format("%032x", new BigInteger(1, bytes));
        } catch (UnsupportedEncodingException e) {
            LOGGER.warn("Encoding error", e);
            throw new IllegalStateException("UTF-8 encoding not available.  Fatal (should be in the JDK).");
        }
    }

}

authz/src/main/java/com/monkeyk/os/domain/oauth/OauthRepository.java
package com.monkeyk.os.domain.oauth;

import com.monkeyk.os.domain.shared.Repository;

import java.util.List;

/**
 * 15-6-13
 *
 * @author Shengzhao Li
 */
public interface OauthRepository extends Repository {

    ClientDetails findClientDetails(String clientId);

    int saveClientDetails(ClientDetails clientDetails);

    int saveOauthCode(OauthCode oauthCode);

    OauthCode findOauthCode(String code, String clientId);

    OauthCode findOauthCodeByUsernameClientId(String username, String clientId);

    int deleteOauthCode(OauthCode oauthCode);

    AccessToken findAccessToken(String clientId, String username, String authenticationId);

    int deleteAccessToken(AccessToken accessToken);

    int saveAccessToken(AccessToken accessToken);

    AccessToken findAccessTokenByRefreshToken(String refreshToken, String clientId);


    List<ClientDetails> findClientDetailsListByClientId(String clientId);
}

authz/src/main/java/com/monkeyk/os/service/dto/ClientDetailsDto.java
package com.monkeyk.os.service.dto;

import com.monkeyk.os.domain.oauth.ClientDetails;
import com.monkeyk.os.infrastructure.DateUtils;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * 2016/6/8
 *
 * @author Shengzhao Li
 */
public class ClientDetailsDto implements Serializable {
    private static final long serialVersionUID = 6642623244436765992L;


    private String resourceIds;

    private String scope;

    private String grantTypes;

    /*
   * Shiro roles
   * */
    private String roles;

    private Integer accessTokenValidity;

    private Integer refreshTokenValidity;

    private boolean trusted;

    private boolean archived;

    private String createTime;


    private String clientId;
    private String clientSecret;

    private String clientName;
    private String clientUri;

    private String clientIconUri;
    private String redirectUri;

    private String description;


    public ClientDetailsDto() {
    }


    public ClientDetailsDto(ClientDetails details) {
        this.clientId = details.getClientId();
        this.clientSecret = details.getClientSecret();
        this.clientName = details.getName();

        this.clientUri = details.getClientUri();
        this.clientIconUri = details.getIconUri();
        this.redirectUri = details.getRedirectUri();

        this.description = details.getDescription();
        this.createTime = DateUtils.toDateTime(details.createTime());
        this.archived = details.archived();

        this.trusted = details.trusted();
        this.refreshTokenValidity = details.refreshTokenValidity();
        this.accessTokenValidity = details.accessTokenValidity();

        this.roles = details.roles();
        this.grantTypes = details.grantTypes();
        this.scope = details.scope();

        this.resourceIds = details.resourceIds();
    }


    public String getResourceIds() {
        return resourceIds;
    }

    public void setResourceIds(String resourceIds) {
        this.resourceIds = resourceIds;
    }

    public String getScope() {
        return scope;
    }

    public void setScope(String scope) {
        this.scope = scope;
    }

    public String getGrantTypes() {
        return grantTypes;
    }

    public void setGrantTypes(String grantTypes) {
        this.grantTypes = grantTypes;
    }

    public String getRoles() {
        return roles;
    }

    public void setRoles(String roles) {
        this.roles = roles;
    }

    public Integer getAccessTokenValidity() {
        return accessTokenValidity;
    }

    public void setAccessTokenValidity(Integer accessTokenValidity) {
        this.accessTokenValidity = accessTokenValidity;
    }

    public Integer getRefreshTokenValidity() {
        return refreshTokenValidity;
    }

    public void setRefreshTokenValidity(Integer refreshTokenValidity) {
        this.refreshTokenValidity = refreshTokenValidity;
    }

    public boolean isTrusted() {
        return trusted;
    }

    public void setTrusted(boolean trusted) {
        this.trusted = trusted;
    }

    public boolean isArchived() {
        return archived;
    }

    public void setArchived(boolean archived) {
        this.archived = archived;
    }

    public String getCreateTime() {
        return createTime;
    }

    public void setCreateTime(String createTime) {
        this.createTime = createTime;
    }

    public String getClientId() {
        return clientId;
    }

    public void setClientId(String clientId) {
        this.clientId = clientId;
    }

    public String getClientSecret() {
        return clientSecret;
    }

    public void setClientSecret(String clientSecret) {
        this.clientSecret = clientSecret;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public String getClientUri() {
        return clientUri;
    }

    public void setClientUri(String clientUri) {
        this.clientUri = clientUri;
    }

    public String getClientIconUri() {
        return clientIconUri;
    }

    public void setClientIconUri(String clientIconUri) {
        this.clientIconUri = clientIconUri;
    }

    public String getRedirectUri() {
        return redirectUri;
    }

    public void setRedirectUri(String redirectUri) {
        this.redirectUri = redirectUri;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public static List<ClientDetailsDto> toDtos(List<ClientDetails> list) {
        List<ClientDetailsDto> dtos = new ArrayList<>(list.size());
        for (ClientDetails clientDetails : list) {
            dtos.add(new ClientDetailsDto(clientDetails));
        }
        return dtos;
    }


    public boolean isContainsAuthorizationCode() {
        return this.grantTypes != null && this.grantTypes.contains("authorization_code");
    }

    public boolean isContainsPassword() {
        return this.grantTypes != null && this.grantTypes.contains("password");
    }

    public boolean isContainsImplicit() {
        return this.grantTypes != null && this.grantTypes.contains("implicit");
    }

    public boolean isContainsClientCredentials() {
        return this.grantTypes != null && this.grantTypes.contains("client_credentials");
    }

    public boolean isContainsRefreshToken() {
        return this.grantTypes != null && this.grantTypes.contains("refresh_token");
    }


}

authz/src/main/java/com/monkeyk/os/web/controller/ClientDetailsController.java
package com.monkeyk.os.web.controller;

import com.monkeyk.os.service.ClientDetailsService;
import com.monkeyk.os.service.dto.ClientDetailsDto;
import com.monkeyk.os.service.dto.ClientDetailsFormDto;
import com.monkeyk.os.service.dto.ClientDetailsListDto;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.PathVariable;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * 2016/6/8
 *
 * @author Shengzhao Li
 */
@Controller
public class ClientDetailsController {


    @Autowired
    private ClientDetailsService clientDetailsService;
    @Autowired
    private ClientDetailsFormDtoValidator validator;


    @RequestMapping(value = "client_details", method = RequestMethod.GET)
    public String clientDetails(String clientId, Model model) {
        ClientDetailsListDto listDto = clientDetailsService.loadClientDetailsListDto(clientId);
        model.addAttribute("listDto", listDto);
        return "oauth/client_details";
    }


    @RequestMapping(value = "client_details/form/plus", method = RequestMethod.GET)
    public String plusUser(Model model) {
        ClientDetailsFormDto formDto = clientDetailsService.loadClientDetailsFormDto();
        model.addAttribute("formDto", formDto);
        return "oauth/client_details_plus";
    }


    @RequestMapping(value = "client_details/form/plus", method = RequestMethod.POST)
    public String submitRegisterClient(@ModelAttribute("formDto") ClientDetailsFormDto formDto, BindingResult result) {
        validator.validate(formDto, result);
        if (result.hasErrors()) {
            return "oauth/client_details_plus";
        }
        clientDetailsService.saveClientDetails(formDto);
        return "redirect:../../client_details";
    }


    /*
    * Test client
    * */
    @RequestMapping("client_details/test_client/{clientId}")
    public String testClient(@PathVariable("clientId") String clientId, Model model) {
        ClientDetailsDto clientDetailsDto = clientDetailsService.loadClientDetailsDto(clientId);
        model.addAttribute("clientDetailsDto", clientDetailsDto);
        return "oauth/test_client";
    }

}

authz/src/main/webapp/WEB-INF/jsp/oauth/client_details.jsp
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="../comm-header.jsp" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Client Details</title>
    <style>
        .list-group li:hover {
            background-color: #f9f9f9;
        }
    </style>
</head>
<body>
<a href="${contextPath}/">Home</a>

<h2>Client Details</h2>

<div class="pull-right">
    <a href="client_details/form/plus" class="btn btn-success">Add Client</a>
</div>
<form action="" class="form-inline">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Type clientId" name="clientId"
               value="${listDto.clientId}"/>
    </div>
    <button type="submit" class="btn btn-default">Search</button>
    &nbsp;<span class="text-info">Total: ${listDto.size}</span>
</form>
<br/>

<div>
    <ul class="list-group">
        <c:if test="${empty listDto.clientDetailsDtos}">
            <li class="list-group-item">
                <p>Empty result</p>
            </li>
        </c:if>
        <c:forEach items="${listDto.clientDetailsDtos}" var="cli">
            <li class="list-group-item">
                <div class="pull-right">
                    <c:if test="${not cli.archived}">
                        <a href="${contextPath}/client_details/test_client/${cli.clientId}">test</a>
                    </c:if>
                    <c:if test="${cli.archived}"><strong class="text-muted">Archived</strong></c:if>
                </div>
                <h3 class="list-group-item-heading">
                        ${cli.clientName}
                    <small>${cli.grantTypes}</small>
                </h3>

                <div class="list-group-item-text text-muted">
                    client_id: <span class="text-danger">${cli.clientId}</span>&nbsp;
                    client_secret: <span class="text-primary">${cli.clientSecret}</span>&nbsp;
                    <br/>
                    grant_types: <span class="text-primary">${cli.grantTypes}</span>&nbsp;
                    resource_ids: <span class="text-primary">${cli.resourceIds}</span>&nbsp;
                    <br/>
                    scope: <span class="text-primary">${cli.scope}</span>&nbsp;
                    redirect_uri: <span class="text-primary">${cli.redirectUri}</span>&nbsp;
                    <br/>
                    roles: <span class="text-primary">${cli.roles}</span>&nbsp;
                    access_token_validity: <span class="text-primary">${cli.accessTokenValidity}</span>&nbsp;
                    refresh_token_validity: <span class="text-primary">${cli.refreshTokenValidity}</span>&nbsp;
                    <br/>
                    client_uri: <span class="text-primary">${cli.clientUri}</span>&nbsp;
                    client_icon_uri: <span class="text-primary">${cli.clientIconUri}</span>&nbsp;
                    <br/>
                    create_time: <span class="text-primary">${cli.createTime}</span>&nbsp;
                    archived: <strong class="${cli.archived?'text-warning':'text-primary'}">${cli.archived}</strong>&nbsp;
                    trusted: <span class="text-primary">${cli.trusted}</span>&nbsp;
                    description: <span class="text-primary">${cli.description}</span>&nbsp;
                </div>
            </li>
        </c:forEach>

    </ul>
    <p class="help-block">
        每一个item对应<code>oauth_client_details</code>表中的一条数据; 共<strong>${listDto.size}</strong>条数据.
    </p>
</div>
</body>
</html>

authz/src/main/webapp/WEB-INF/jsp/oauth/oauth_approval.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<!DOCTYPE HTML>

<html>
<head>
    <title>Oauth Approval</title>
</head>
<body><h1>OAuth Approval</h1>

<p>Do you authorize '${param.client_id}' to access your protected resources?</p>

<form id='confirmationForm' name='confirmationForm' action='${pageContext.request.contextPath}/oauth/authorize'
      method='post'>
    <input type="hidden" name="client_id" value="${param.client_id}"/>
    <input type="hidden" name="scope" value="${param.scope}"/>
    <input type="hidden" name="response_type" value="${param.response_type}"/>
    <input type="hidden" name="redirect_uri" value="${param.redirect_uri}"/>
    <input type="hidden" name="state" value="${param.state}"/>
    <input type="hidden" name="client_secret" value="${param.client_secret}"/>

    <input name='user_oauth_approval' value='true' type='hidden'/>
    <label> <input value='Authorize' type='submit' class="btn btn-success"/></label>
</form>

<form id='denialForm' name='denialForm' action='${pageContext.request.contextPath}/oauth/authorize' method='post'>
    <input type="hidden" name="client_id" value="${param.client_id}"/>
    <input type="hidden" name="scope" value="${param.scope}"/>
    <input type="hidden" name="response_type" value="${param.response_type}"/>
    <input type="hidden" name="redirect_uri" value="${param.redirect_uri}"/>
    <input type="hidden" name="state" value="${param.state}"/>
    <input type="hidden" name="client_secret" value="${param.client_secret}"/>

    <input name='user_oauth_approval' value='false' type='hidden'/>
    <label><input value='Deny' type='submit' class="btn btn-warning"/></label>
</form>
</body>
</html>

authz/src/main/webapp/WEB-INF/jsp/oauth/oauth_login.jsp
<%--
 * Copyright (c) 2013 Andaily Information Technology Co. Ltd
 * www.andaily.com
 * All rights reserved.
 *
 * This software is the confidential and proprietary information of
 * Andaily Information Technology Co. Ltd ("Confidential Information").
 * You shall not disclose such Confidential Information and shall use
 * it only in accordance with the terms of the license agreement you
 * entered into with Andaily Information Technology Co. Ltd.
--%>
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="../comm-header.jsp" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Oauth Login</title>
</head>
<body>

<div class="row">
    <h3>Oauth Login</h3>

    <p>
        登录使用的 client_id: '${param.client_id}'.
    </p>

    <div class="row">
        <div class="col-md-5">
            <form action="${pageContext.request.contextPath}/oauth/authorize" method="post" class="form-horizontal">
                <input type="hidden" name="client_id" value="${param.client_id}"/>
                <input type="hidden" name="scope" value="${param.scope}"/>
                <input type="hidden" name="response_type" value="${param.response_type}"/>
                <input type="hidden" name="redirect_uri" value="${param.redirect_uri}"/>
                <input type="hidden" name="state" value="${param.state}"/>
                <input type="hidden" name="client_secret" value="${param.client_secret}"/>

                <div class="form-group">
                    <label class="col-sm-3 control-label">Username</label>

                    <div class="col-sm-9">
                        <input type="text" name="username" value="" required="required" class="form-control"
                               placeholder="Type username"/>
                    </div>
                </div>
                <div class="form-group">
                    <label class="col-sm-3 control-label">Password</label>

                    <div class="col-sm-9">
                        <input type="password" name="password" required="required" class="form-control"
                               placeholder="Type password"/>
                    </div>
                </div>
                <div class="form-group">
                    <div class="col-sm-offset-2 col-sm-10">
                        <input type="submit" value="Login" class="btn btn-primary"/>
                        &nbsp;
                        <span style="color:red;"><c:if test="${not empty oauth_login_error}">Login failed</c:if></span>
                    </div>
                </div>
            </form>
        </div>
    </div>
    <%--<form action="${pageContext.request.contextPath}/oauth/authorize" method="post">--%>
    <%--<input type="hidden" name="client_id" value="${param.client_id}"/>--%>
    <%--<input type="hidden" name="scope" value="${param.scope}"/>--%>
    <%--<input type="hidden" name="response_type" value="${param.response_type}"/>--%>
    <%--<input type="hidden" name="redirect_uri" value="${param.redirect_uri}"/>--%>
    <%--<input type="hidden" name="state" value="${param.state}"/>--%>
    <%--<input type="hidden" name="client_secret" value="${param.client_secret}"/>--%>

    <%--Username: <input type="text" name="username" value="" required="required"/>--%>
    <%--<br/> <br/>--%>
    <%--Password: <input type="password" name="password" required="required"/>--%>
    <%--<br/> <br/>--%>
    <%--<input type="submit" value="Login" class="btn btn-primary"/>--%>
    <%--<br/>--%>
    <%--<span style="color:red;"><c:if test="${not empty oauth_login_error}">Login failed</c:if></span>--%>
    <%--</form>--%>
</div>

<div>
    <br/>

    <p>可以使用下面的账号登录或使用你自行添加的账号:</p>
    <table class="table table-bordered">
        <thead>
        <tr>
            <th>username</th>
            <th>password</th>
            <th>grant_types</th>
            <th>roles</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <td>test</td>
            <td>test</td>
            <td>authorization_code,password,refresh_token,client_credentials</td>
            <td>User(id=22)</td>
        </tr>
        </tbody>
    </table>
</div>
</body>
</html>

authz/src/main/webapp/WEB-INF/jsp/oauth/test_client.jsp
<%--
 * 
 * @author Shengzhao Li
--%>

<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Test [${clientDetailsDto.clientId}]</title>

    <script src="${contextPath}/resources/angular.min.js"></script>

</head>
<body>
<div ng-app>
    <a href="${contextPath}/">Home</a>

    <h2>Test [${clientDetailsDto.clientId}]</h2>

    <p>
        针对不同的<code>grant_type</code>提供不同的测试URL,
        完整的OAuth测试请访问<a href="http://git.oschina.net/mkk/spring-oauth-client" target="_blank">spring-oauth-client</a>项目.
    </p>

    <div ng-controller="TestClientCtrl">
        <c:if test="${clientDetailsDto.containsAuthorizationCode}">
            <div class="panel panel-default">
                <div class="panel-heading">Test [authorization_code]</div>
                <div class="panel-body">
                    <p class="text-muted">输入每一步必要的信息后点击其下面的链接地址.</p>
                    <ol>
                        <li>
                            <p>
                                <code>从 oauth-shiro 获取 'code'</code>
                                <br/>
                                redirect_uri: <input type="text" value="" ng-model="redirectUri" size="70"
                                                     required="required"/>
                                <br/>
                                <a href="${contextPath}/oauth/authorize?client_id={{clientId}}&redirect_uri={{redirectUri}}&response_type=code&scope={{scope}}&state=123456"
                                   target="_blank">
                                    /oauth/authorize?client_id={{clientId}}&redirect_uri={{redirectUri}}&response_type=code&scope={{scope}}&state=123456</a>
                                <span class="label label-info">GET</span>
                            </p>
                        </li>
                        <li>
                            <code>用 'code' 换取 'access_token'</code>
                            <br/>
                            输入第一步获取的code: <input type="text" name="code" value="" ng-model="code"
                                                 required="required"/>
                            <br/>

                            <form action="${contextPath}/oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=authorization_code&code={{code}}&redirect_uri={{redirectUri}}"
                                  method="post" target="_blank">
                                <button class="btn btn-link" type="submit">
                                    /oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=authorization_code&code={{code}}&redirect_uri={{redirectUri}}
                                </button>
                                <span class="label label-warning">POST</span>
                            </form>
                        </li>
                    </ol>
                </div>
            </div>
        </c:if>

        <c:if test="${clientDetailsDto.containsPassword}">
            <div class="panel panel-default">
                <div class="panel-heading">Test [password]</div>
                <div class="panel-body">
                    <p class="text-muted">输入username, password 后点击链接地址.</p>
                    username: <input type="text" required="required" ng-model="username"/>
                    <br/>
                    password: <input type="text" required="required" ng-model="password"/>

                    <br/>

                    <form action="${contextPath}/oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=password&scope={{scope}}&username={{username}}&password={{password}}"
                          method="post" target="_blank">
                        <button class="btn btn-link" type="submit">
                            /oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=password&scope={{scope}}&username={{username}}&password={{password}}
                        </button>
                        <span class="label label-warning">POST</span>
                    </form>
                </div>
            </div>
        </c:if>

        <c:if test="${clientDetailsDto.containsImplicit}">
            <div class="panel panel-default">
                <div class="panel-heading">Test [implicit]</div>
                <div class="panel-body">
                    <p class="text-muted">输入redirect_uri 后点击链接地址. 获取access_token后注意查看redirect_uri的hash部分(#号后边部分)</p>
                    redirect_uri: <input type="text" value="" ng-model="implicitRedirectUri" size="70"
                                         required="required"/>

                    <p>
                        <a href="${contextPath}/oauth/authorize?client_id={{clientId}}&response_type=token&scope={{scope}}&redirect_uri={{implicitRedirectUri}}"
                                >/oauth/authorize?client_id={{clientId}}&response_type=token&scope={{scope}}&redirect_uri={{implicitRedirectUri}}</a>
                        <span class="label label-info">GET</span>
                    </p>
                </div>
            </div>
        </c:if>

        <c:if test="${clientDetailsDto.containsClientCredentials}">
            <div class="panel panel-default">
                <div class="panel-heading">Test [client_credentials]</div>
                <div class="panel-body">
                    <p class="text-muted">点击链接地址即可测试</p>


                    <form action="${contextPath}/oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=client_credentials&scope={{scope}}"
                          method="post" target="_blank">
                        <button class="btn btn-link" type="submit">
                            /oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=client_credentials&scope={{scope}}
                        </button>
                        <span class="label label-warning">POST</span>
                    </form>
                </div>
            </div>
        </c:if>

        <c:if test="${clientDetailsDto.containsRefreshToken}">
            <div class="panel panel-default">
                <div class="panel-heading">Test [refresh_token]</div>
                <div class="panel-body">
                    <p class="text-muted">输入refresh_token 后点击链接地址.</p>
                    refresh_token: <input type="text" ng-model="refreshToken" required="required" size="70"/>

                    <br/>

                    <form action="${contextPath}/oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=refresh_token&refresh_token={{refreshToken}}"
                          method="post" target="_blank">
                        <button class="btn btn-link" type="submit">
                            /oauth/token?client_id={{clientId}}&client_secret={{clientSecret}}&grant_type=refresh_token&refresh_token={{refreshToken}}
                        </button>
                        <span class="label label-warning">POST</span>
                    </form>
                </div>
            </div>
        </c:if>

        <div class="text-center">
            <a href="${contextPath}/client_details" class="btn btn-default">Back</a>
        </div>
    </div>
</div>

<script>
    var TestClientCtrl = ["$scope", function ($scope) {
        $scope.clientId = "${clientDetailsDto.clientId}";
        $scope.clientSecret = "${clientDetailsDto.clientSecret}";
        $scope.scope = "${clientDetailsDto.scope}";

        <c:if test="${empty clientDetailsDto.redirectUri}" var="eptRedUri">
        $scope.implicitRedirectUri = location.href;
        $scope.redirectUri = "";
        </c:if>
        <c:if test="${not eptRedUri}">
        $scope.implicitRedirectUri = "${clientDetailsDto.redirectUri}";
        $scope.redirectUri = "${clientDetailsDto.redirectUri}";
        </c:if>

        $scope.username = "test";
        $scope.password = "test";
        //a temp value
        $scope.refreshToken = "1156ebfe-e303-4572-9fb5-4459a5d46610";

    }];
</script>
</body>
</html>