authz/src/main/java/com/monkeyk/os/domain/users/PasswordHandler.java
package com.monkeyk.os.domain.users;


import java.io.UnsupportedEncodingException;
import java.math.BigInteger;
import java.security.MessageDigest;
import java.security.NoSuchAlgorithmException;

/**
 * 2016/3/25
 * <p/>
 * 账号密码的加密 处理类
 * 使用MD5
 *
 * @author Shengzhao Li
 */
public abstract class PasswordHandler {


    private PasswordHandler() {
    }


    public static String md5(String password) {

        MessageDigest digest;
        try {
            digest = MessageDigest.getInstance("MD5");
        } catch (NoSuchAlgorithmException e) {
            throw new IllegalStateException("MD5 algorithm not available.  Fatal (should be in the JDK).");
        }

        try {
            byte[] bytes = digest.digest(password.getBytes("UTF-8"));
            return String.format("%032x", new BigInteger(1, bytes));
        } catch (UnsupportedEncodingException e) {
            throw new IllegalStateException("UTF-8 encoding not available.  Fatal (should be in the JDK).");
        }

    }
}

authz/src/main/java/com/monkeyk/os/domain/users/UsersAuthzRepository.java
package com.monkeyk.os.domain.users;

import com.monkeyk.os.domain.shared.Repository;

import java.util.List;

/**
 * 2016/6/3
 *
 * @author Shengzhao Li
 */

public interface UsersAuthzRepository extends UsersRepository {

    List<Users> findUsersByUsername(String username);

    List<Roles> findAvailableRolesList();

    Users findByUsername(String username);

    int saveUsers(Users users);

    Roles findRolesByGuid(String guid);

    void insertUserRoles(int userId, int rolesId);
}

authz/src/main/java/com/monkeyk/os/service/dto/UsersOverviewDto.java
package com.monkeyk.os.service.dto;

import com.monkeyk.os.domain.users.Users;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.List;

/**
 * 2016/6/3
 *
 * @author Shengzhao Li
 */
public class UsersOverviewDto implements Serializable {
    private static final long serialVersionUID = 4895901148003956952L;

    private List<UsersDto> usersDtos = new ArrayList<>();

    private String username;

    public UsersOverviewDto() {
    }

    public UsersOverviewDto(List<Users> usersList, String username) {
        this.usersDtos = UsersDto.toDtos(usersList);
        this.username = username;
    }

    public int getUsersSize() {
        return usersDtos.size();
    }


    public List<UsersDto> getUsersDtos() {
        return usersDtos;
    }

    public void setUsersDtos(List<UsersDto> usersDtos) {
        this.usersDtos = usersDtos;
    }

    public String getUsername() {
        return username;
    }

    public void setUsername(String username) {
        this.username = username;
    }
}

authz/src/main/java/com/monkeyk/os/web/controller/UsersController.java
package com.monkeyk.os.web.controller;

import com.monkeyk.os.service.UserService;
import com.monkeyk.os.service.dto.UsersFormDto;
import com.monkeyk.os.service.dto.UsersOverviewDto;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.ui.Model;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.ModelAttribute;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;

/**
 * 2016/6/3
 *
 * @author Shengzhao Li
 */
@Controller
@RequestMapping("/users/")
public class UsersController {


    @Autowired
    private UserService userService;

    @Autowired
    private UsersFormDtoValidator validator;


    @RequestMapping(value = "overview", method = RequestMethod.GET)
    public String overview(String username, Model model) {
        UsersOverviewDto overviewDto = userService.loadUsersOverviewDto(username);
        model.addAttribute("overviewDto", overviewDto);
        return "users/users_overview";
    }


    @RequestMapping(value = "form/plus", method = RequestMethod.GET)
    public String plusUser(Model model) {
        UsersFormDto formDto = userService.loadUsersFormDto();
        model.addAttribute("formDto", formDto);
        return "users/user_plus";
    }


    @RequestMapping(value = "form/plus", method = RequestMethod.POST)
    public String submitRegisterClient(@ModelAttribute("formDto") UsersFormDto formDto, BindingResult result) {
        validator.validate(formDto, result);
        if (result.hasErrors()) {
            return "users/user_plus";
        }
        userService.saveUsers(formDto);
        return "redirect:../overview";
    }


}

authz/src/main/webapp/WEB-INF/jsp/users/user_plus.jsp
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="../comm-header.jsp" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Add User</title>
</head>
<body>
<a href="../">Home</a>

<h2>Add User</h2>


<form:form commandName="formDto" cssClass="form-horizontal">
    <div class="form-group">
        <label class="col-sm-2 control-label">Username<em class="text-danger">*</em></label>

        <div class="col-sm-10">
            <form:input path="username" cssClass="form-control" placeholder="Type username"
                        required="required"/>

            <p class="help-block">Username, unique.</p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Password<em class="text-danger">*</em></label>

        <div class="col-sm-10">
            <form:password path="password" cssClass="form-control" placeholder="Type password"
                           required="required"/>

            <p class="help-block">Password, required.</p>
        </div>
    </div>
    <div class="form-group">
        <label class="col-sm-2 control-label">Roles<em class="text-danger">*</em></label>

        <div class="col-sm-10">
            <c:forEach items="${formDto.rolesDtos}" varStatus="vs" var="role">
                <input type="hidden" name="rolesDtos[${vs.index}].guid" value="${role.guid}"/>
                <input type="hidden" name="rolesDtos[${vs.index}].roleName" value="${role.roleName}"/>

                <label class="checkbox">
                    <form:checkbox path="roleGuids" value="${role.guid}"/> ${role.roleName} ${role.permissions}
                </label>
            </c:forEach>

            <p class="help-block">Select Roles</p>
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-2"></div>
        <div class="col-sm-10">
            <form:errors path="*" cssClass="label label-warning"/>
        </div>
    </div>


    <div class="form-group">
        <div class="col-sm-2"></div>
        <div class="col-sm-10">
            <button type="submit" class="btn btn-success">Save</button>
            <a href="../overview">Cancel</a>
        </div>
    </div>
</form:form>


</body>
</html>

authz/src/main/webapp/WEB-INF/jsp/users/users_overview.jsp
<%--
 * 
 * @author Shengzhao Li
--%>
<%@ page contentType="text/html;charset=UTF-8" language="java" %>
<%@ include file="../comm-header.jsp" %>
<!DOCTYPE HTML>
<html>
<head>
    <title>Users</title>
</head>
<body>
<a href="../">Home</a>

<h2>Users</h2>

<div class="pull-right">
    <a href="form/plus" class="btn btn-success btn-sm">Add User</a>
</div>
<form action="" class="form-inline">
    <div class="form-group">
        <input type="text" class="form-control" placeholder="Type username" name="username"
               value="${overviewDto.username}"/>
    </div>
    <button type="submit" class="btn btn-default">Search</button>
    &nbsp;<span class="text-info">Total: ${overviewDto.usersSize}</span>
</form>
<br/>
<table class="table table-bordered table-hover table-striped">
    <thead>
    <tr>
        <th>Username</th>
        <th>Roles[permission]</th>
        <th>CreateTime</th>
    </tr>
    </thead>
    <tbody>
    <c:forEach items="${overviewDto.usersDtos}" var="user">
        <tr>
            <td>${user.username}</td>
            <td><c:forEach items="${user.rolesDtos}" var="r"
                           varStatus="vs">${r.roleName} ${r.permissions}${vs.last?'':','}</c:forEach></td>
            <td>${user.createTime}</td>
        </tr>
    </c:forEach>
    </tbody>
</table>
</body>
</html>